Adding functions PFArray
anchutkina/object_array pull request #1
Opened 2023-03-20 16:18 UTC by anchutkina

Doplnila jsem funkcí, co by měly byt zapouzdřeny uvnitř objektu PFArray.

2023-03-21 06:58 UTC, tomasma5 requested changes
Prosím o změny viz komentáře

2023-03-21 06:58 UTC, tomasma5 commented on .idea/compiler.xml
Přidej si gitignore file - tohle by v commitě být nemělo (celá složka idea. a pak soubor object_array.iml

2023-03-21 06:58 UTC, tomasma5 commented on README.md
Prosím více popsat v rámci Readme.MD co v tomto projektu je, k čemu slouží, jak ho spustíš a zbuildíš.

2023-03-21 06:58 UTC, tomasma5 commented on object_array.iml
Má být v gitignore

2023-03-21 06:58 UTC, tomasma5 commented on src/main/java/org/example/Main.java
prosím o správné package - udělej normálně src/main/java/cz/pf/array

2023-03-21 06:58 UTC, tomasma5 commented on src/main/java/org/example/Main.java
> +//        int abc[] = {2,5,10,16};
prosím odstranit zakomentovaný text

2023-03-21 06:58 UTC, tomasma5 commented on src/main/java/org/example/Main.java
Třída jako taková ještě neřeší co má, ale beru že to je první verze a dál na tom budeš pracovat :)

2023-03-21 06:58 UTC, tomasma5 commented on target/classes/org/example/Main.class
Přidat do gitignore

2023-03-21 06:58 UTC, tomasma5 commented on target/classes/org/example/PFArray.class
Přidat do gitignore

2023-03-21 06:58 UTC, tomasma5 commented on test.txt
Přidat do gitignore

2023-03-21 09:56 UTC, anchutkina commented on src/main/java/org/example/Main.java
> Třída jako taková ještě neřeší co má, ale beru že to je první verze a dál na tom budeš pracovat :)
@tomasma5
Máš na mysli, že třida neobsahuje všechny funkce co by měla?

2023-03-21 22:05 UTC, tomasma5 commented on src/main/java/org/example/Main.java
jj a hlavně ti to ještě nedělá to co by mělo. Měla bys mít menu, které drží, můžeš ho ovládat a pod :)

2023-03-21 22:05 UTC, tomasma5 requested changes
Prosím o zapracování změn.

2023-03-24 14:44 UTC, tomasma5 requested changes
Prosím o změny.

2023-03-24 14:44 UTC, tomasma5 commented on .idea/uiDesigner.xml
Přibyl ti další soubor - evidentně ti ten gitignore správně nefunguje.

2023-03-24 14:44 UTC, tomasma5 commented on src/main/java/cz/pf/Main.java
> +            arr[i] = (int) (Math.random() * 10);
proč to násobíš 10? https://www.educative.io/answers/how-to-generate-random-numbers-in-java - generuj v maximálním rozsahu Integeru.

2023-03-24 14:44 UTC, tomasma5 commented on src/main/java/cz/pf/Main.java
> +        String chosenCreationType = scanner.nextLine();
dal bych pryč to chosen a nechal jen arrayCreatinType ;) ať proměnná říká co znamená.

2023-03-24 14:44 UTC, tomasma5 commented on src/main/java/cz/pf/Main.java
> +        if (chosenCreationType.equals("random")) {
"random" - přijde tohle jako konstantu do rootu třídy. (privat final static String= "random"; a pak to tady jen použíj. Popřípadě to udělej jako enum

2023-03-24 14:44 UTC, tomasma5 commented on src/main/java/cz/pf/Main.java
> +            PFArray pfArray = new PFArray(generateRandomNumbers(Integer.valueOf(chosenSize)));
Tohle je ok, al už nikdy s tím pfArray nebudeš přeci moct pracovat. Jak nad ním pak budeš dělat další akce?

2023-03-24 14:44 UTC, tomasma5 commented on src/main/java/cz/pf/Main.java
> +            chooseNameOfArray(scanner, pfArray);
Tohle není dobrý pattern. Strašně se to dělí. Udělej to tak, že ti uživatel zadá nejprve název a pak velikost pole. Protože název je společný pro oba typy generování pole. a nebudeš tu mít 100 malých metod.

2023-03-24 14:44 UTC, tomasma5 commented on src/main/java/cz/pf/Main.java
> +        for(int i = 0; i < arrayStorage.size(); i++) {
Tohle bych třeba vytáhl bokem do metody. findArrayByName. Neprocházej to podle arrayStorage.size() ale přes iterator, nebo pomocí dvojtečky - tady je článek: https://www.geeksforgeeks.org/iterating-arraylists-java/

2023-03-24 14:44 UTC, tomasma5 commented on src/main/java/cz/pf/Main.java
> +        pfArray.setName(nameOfArray);
na objektu pfArray bych neměl metodu setName, ale jméno bych nastavil v rámci konstruktoru.

2023-03-24 14:44 UTC, tomasma5 commented on src/main/java/cz/pf/Main.java
> +    private static void printCreatedArray(Scanner scanner, PFArray pfArray) {
Tahle metoda je zbytečná. Neptej se - vypiš mu, že jsi vytvořila pole s tímto názvem a vytiskni ho.

2023-03-24 14:44 UTC, tomasma5 commented on src/main/java/cz/pf/Main.java
> +        System.out.println("Choose and type option from following:\n'create' --to create a new array\n'select' --to select the array to work with\n'largest sum' --to find the array with the largest s
Tady bych použil čísla - kvůli volbám - 1, 2 atd. ne create, select apod.

2023-03-24 14:44 UTC, tomasma5 commented on src/main/java/cz/pf/Main.java
> +            workWithArray(scanner, pfArray);
bohužel to nemůžeš dělat takhle, protože by se ti to nořilo do sebe a rekurzivně volalo. WorkWitharray je v principu nekonečný while cyklus, v který běží pořád do kola a vždy ti nabídne co chceš dělat. Zavoláš funkci, ona to udělá a skončí a protože je v nekonečném while cyklu tak se znovu zeptá na další volbu. Tohle volání funkce na funkci není správný pattern.

2023-03-24 14:44 UTC, tomasma5 commented on src/main/java/cz/pf/Main.java
> +        arrayStorage.forEach((e) -> System.out.println(e.getName()));
Proč tady používáš Lambdu (pokročilá Java) a o 15 řádků výše pracuješ s polem tak, že pomocí for cyklu a size getuješ pole s arraylistu?

2023-03-24 14:44 UTC, tomasma5 commented on src/main/java/cz/pf/Main.java
> +        System.out.println("Choose and type option from following:\n'print' --to print selected array\n'add' --to add number to the selected array\n'remove' --to remove number from the selected array
to samé jako v rámci work with array. tohle je potřeba předělat a nevolat rekurzivně. Pozor na toto: https://www.w3schools.com/java/java_recursion.asp

2023-03-24 14:44 UTC, tomasma5 commented on src/main/java/cz/pf/Main.java
> +        for(int i = 0; i < arrayStorage.size(); i++) {
předělat procházení pole viz výše.

2023-03-24 14:44 UTC, tomasma5 commented on src/main/java/cz/pf/array/PFArray.java
> +    public PFArray(int[] array) {
tento konstruktur nebudeš potřebovat.

2023-03-24 14:44 UTC, tomasma5 commented on src/main/java/cz/pf/array/PFArray.java
> +    public String setName(String nameOfArray) {
pokud máš getter nebo setter tak ten má jasně danou funkcionalitu. Tzn setter nemůže vracet hodnoty. Měla bys udělat pfarray.setName("ahoj")
pfarray.getName() - vrátí ti ahoj
Kromě toho setter dej pryč. V tomto kontextu by se metoda měla jmenovat rename.

2023-03-24 14:44 UTC, tomasma5 commented on src/main/java/cz/pf/array/PFArray.java
> +    public int[] deleteArray(){
proč vracíš pole. metoda smaže pole tzn neměla by ho vracet.

2023-03-24 14:44 UTC, tomasma5 commented on src/main/java/cz/pf/array/PFArray.java
> +    public int[] regenerateArray() {
tohle dej pryč. budeš to generovat v main. tady to být nemusí

2023-03-24 14:44 UTC, tomasma5 commented on src/main/java/cz/pf/array/PFArray.java
> +    public int[] removeSelNumberFromArray(int rmIndex) {
nevracej pole není k tomu důvod. uživatel zavolá removeSel... a pak zavolá printArray

2023-03-24 14:44 UTC, tomasma5 commented on src/main/java/cz/pf/array/PFArray.java
> +    public int[] removeNumberFromArray() {
nevracej pole není k tomu důvod. uživatel zavolá remove..... a pak zavolá printArray

2023-03-24 14:44 UTC, tomasma5 commented on src/main/java/cz/pf/array/PFArray.java
> +    public int[] addNumberToArray(int newNumber) {
Opět jako ve zbytku nedávej to pole z objektu ;)

2023-03-24 14:44 UTC, tomasma5 commented on src/main/java/cz/pf/array/PFArray.java
> +    public int[] getArray() {
Tohle nebudeš potřebovat. Používej printArray - getArray umožní, že ti ho někdo změní mimo tento objekt.

2023-03-27 13:19 UTC, anchutkina commented on src/main/java/cz/pf/Main.java
> +        arrayStorage.forEach((e) -> System.out.println(e.getName()));
Zatím moc neumím rozlišit, jestli to je pokročilá nebo ne :) Jen jsem viděla forEach v nějakém článku, když jsem hledala něco jiného a chtěla jsem to zkusit, mám to změnit na for cyklus?
@tomasma5

2023-03-27 13:21 UTC, tomasma5 commented on src/main/java/cz/pf/Main.java
> +        arrayStorage.forEach((e) -> System.out.println(e.getName()));
Ano pls

2023-03-27 13:51 UTC, anchutkina commented on src/main/java/cz/pf/Main.java
> +            workWithArray(scanner, pfArray);
Myslela jsem si, že chceme aby uživatel pokračoval pokud nebude chtít ten program ukončit. Není to tak? Správně chápu, že program se musí ukončit když najde třeba největší/nejmenší sumu?
@tomasma5

2023-04-02 18:33 UTC, tomasma5 requested changes
Prosím o změny. Dávej si pozor na:

- Pojmenování metod a proměnných. Hodně metod se tváří jako proměnná, tudíž vůbec nevím co mohou dělat
- Ohraničení toho co metoda dělá a toho co už nedělá - nemůžeš mít v metodě chooseArrayName skryté i generování pole.
- + Všechny moje komentáře ;)

2023-04-02 18:33 UTC, tomasma5 commented on src/main/java/cz/pf/Main.java
> +    private static PFArray pfArray = new PFArray();
Tuhle proměnou vůbec nepotřebuješ. Odstraň ji pls.

2023-04-02 18:33 UTC, tomasma5 commented on src/main/java/cz/pf/Main.java
> +    private static void chooseNameOfArray(Scanner scanner) {
přejmenuj pls na chooseArrayName - je to přímočařejší. Současně by ti tato metoda měla vrátit jméno. Ale ono ti k tomu i vytvoří pole což není dobře. Předělej tedy prosím tak, aby návratový typ byl string a až na jeho základě si zavolala založení pole.

2023-04-02 18:33 UTC, tomasma5 commented on src/main/java/cz/pf/Main.java
> +    private static void chooseNameOfArray(Scanner scanner) {
V metodě se musíš vypořádat i s tím, že si to jméno už někdo vybral. Tzn pokud zadám jméno pole, které tam je, tak mi musíš řict. Jméno je již obsazeno, vyberte si další. Nemůžeš jen tak skončit ;)

2023-04-02 18:33 UTC, tomasma5 commented on src/main/java/cz/pf/Main.java
> +                arrayCreatingType(scanner);
Toto tady nemůže být - protože v metodě řešíš název pole a ne jeho vytvoření.

2023-04-02 18:33 UTC, tomasma5 commented on src/main/java/cz/pf/Main.java
> +    private static boolean findArrayByName(String nameOfArray) {
Tato metoda nedává smysl. Jmenuje se findArrayByName, ale vrací true nebo false. To mi nepřijde jako jméno pole,

2023-04-02 18:33 UTC, tomasma5 commented on src/main/java/cz/pf/Main.java
> +    private static void arrayCreatingType(Scanner scanner) {
Prosím přejmenovat - vůbec nevím podle názvu co dělá. Když si to domyslím podle kódu, tak bych čekal, že mi vrátí pole.

Obecně není dobrý pattern, když máš metody, které nic nevrací, ale jen je za sebe řetězíš.

2023-04-02 18:33 UTC, tomasma5 commented on src/main/java/cz/pf/Main.java
> +    private static void numbersInManualArray(Scanner scanner) {
Opět nevím co metoda dělá. protože se jmenuje jako proměnná :-(

Obecně název proměnné například: favouriteNumber
Obecně název metody: generateFavouriteNumber, chooseFavouriteNumber, findFavouriteNumber - nikdy ne favouriteNumberInField

2023-04-02 18:33 UTC, tomasma5 commented on src/main/java/cz/pf/Main.java
> +    private static void actionsWithArray(Scanner scanner, PFArray pfArray) {
Opět prosím přejmenovat - vypadá to jako název proměnné ne metody.

2023-04-03 19:31 UTC, tomasma5 requested changes
Už se blížíš ;)

2023-04-03 19:31 UTC, tomasma5 commented on src/main/java/cz/pf/Main.java
> +            if (chosenOption == 1) {
Pozor na spelling není to náhodou choosen? :)

2023-04-03 19:31 UTC, tomasma5 commented on src/main/java/cz/pf/Main.java
> +        System.out.println("Please provide name of array you want to create:");
Z této metody bys ho neměla pustit, pokud si nevybere jméno. protože pak se ti stane, že bude muset znovu projít celým procesem

2023-04-03 19:31 UTC, tomasma5 commented on src/main/java/cz/pf/Main.java
> +    private static String chooseArrayType(Scanner scanner) {
Opět tady bys měla řešit, že se trefíš do volby. Měla by z metody vypadnout vždy relevantní hodnota.

2023-04-03 19:31 UTC, tomasma5 commented on src/main/java/cz/pf/Main.java
> +                    System.err.println("The entered value is incorrect.");
Tenhle else musíš vyřešit v chooseArrayType

2023-04-03 19:31 UTC, tomasma5 commented on src/main/java/cz/pf/Main.java
> +    private static int[] inputManualNumbers(Scanner scanner) {
inputManualNumbers není název metody generateArrayManually apod je ten správný název

2023-04-03 19:31 UTC, tomasma5 commented on src/main/java/cz/pf/Main.java
> +            if (chosenOption == 1) {
Chybí ti tu kontrola, že vůbec něco existuje. Když zapnu program a dám volbu 2 tak mi to pak zřejmě spadne ne? :)

2023-04-03 19:31 UTC, tomasma5 commented on src/main/java/cz/pf/Main.java
> +                } else if (actionWithArray == 3) {
Pls místo 3 si udělej konstantu, která říká co ta trojka je. Stejně pro ostatní části

2023-04-03 19:31 UTC, tomasma5 commented on src/main/java/cz/pf/Main.java
> +                    System.out.println("Number is added. Updated array: " + pfArray.toString() + "\n");
Nebylo by jednodušší, vytisknout číslo, které chci a rovnou předat ten scanner.nextInt() do metody addNumberToArray a pak udělat scanner.nextLine()? jde o to, jestli je tady nutné pracovat s tím newNumber ;)

2023-04-05 08:42 UTC, anchutkina commented
1. Konstanty místo čísel jsem přidala pomocí enum, abych neměla 12 konstant v Main, může to tak být?
2. Přidala jsem kontrolu existuje-li nějaký array v mainu ve volbě 2,3,4 zvlášť, protože 1 a 5 volba to nepotřebuje. Musí to být jedna kontrola na začátku, nebo takhle v pohodě?
3. Přidala jsem try-catch v částích, kde musí user zadat číslo, aby program nespadnul, když zadá string. Jenže když user projde celým procesem a v druhém menu (po selectu pole s kterým chce pracovat) zadá string, tak ho program vrátí úplně na začátek. Řešení vidím ve vytvoření dalšího while před druhým menu. Je to ok, nebo mám vyhledat jiné řešení, nebo nechat jak to je? 
4. Doplnila jsem chooseArrayType a chooseArrayName pomocí while loopů, aby metoda nepustila uživatele pokud nezadá relevantní hodnotu. 
5. Metoda selectArray pří zadaní neexistujícího jména napíše že takový array neexistuje a převede uživatele na začátek, místo toho aby zase uvedl jméno. Pomocí while se mi to nepodařilo opravit. A žádný jiný způsob bez rekurze jsem nenašla. Můžu poprosit o radu co s tím?

2023-04-05 08:48 UTC, tomasma5 requested changes
AD 1) OK,
Zbytek okomentováno. Prosím o drobné změny :)

2023-04-05 08:48 UTC, tomasma5 commented on src/main/java/cz/pf/ActionWithArray.java
> +    final int i;
co je int i? není to náhodou value? prostě i je magic constanta ;)

2023-04-05 08:48 UTC, tomasma5 commented on src/main/java/cz/pf/Main.java
> +                if (chosenOption == OptionWithArray.CREATE_ARRAY.i) {
Tady je přesně důsledek toho i. Když to čtu tak nevím co je i :) Kdyby to bylo CREATE_ARRAY.OptionId tak mi to dává smysl

2023-04-05 08:48 UTC, tomasma5 commented on src/main/java/cz/pf/Main.java
> +        while(arrayName.isBlank() || isUnique == false) {
Jak z toho uživatel uteče? Má možnost říct, že si to rozmyslel? Tzn měla by ses ho zeptat jestli chce zadat vstup znovu nebo nikoliv. :)

2023-04-05 10:57 UTC, tomasma5 requested changes
Prosím o změny

2023-04-05 10:57 UTC, tomasma5 commented on src/main/java/cz/pf/Main.java
> +        for (PFArray i : arrayStorage) {
Nepoužívej i. Je to přece PFArray, proč se to jmenuje i? Měj PFArray pfArray : arrayStorage. To je jako bys udělal:
Wallet h = new Wallet();
Money fn = new Money(100);

a pak někde dál si udělala:
if(fn<20) h.add(fn) - tušíš co tento řádek dělá? Kdyby byl správně pojmenovaný tak by to třeba vypadalo takto

Wallet wallet = new Wallet();
Money myCashMoney = new Money(100);
if(myCashMoney<20) wallet.add(myCashMoney); - lepší ne?

2023-04-05 10:57 UTC, tomasma5 commented on src/main/java/cz/pf/Main.java
> +        for (PFArray i : arrayStorage) {
Tady si musíš pak definovat to array, které uživatel chce vybrat PFArray selectedArray=null; Když ho najdeš tak selectedArraay=pfArray Když nanajdeš tka je null. While cykl testuje jestli je selectedArray různé od null, pokud není tak ho vyzveš ať znovu zadá vstup a tak dále ;)

2023-04-05 10:57 UTC, tomasma5 commented on src/main/java/cz/pf/Main.java
> +            for (PFArray i : arrayStorage) {
Prosím projdi to všechno a začni používat správné proměnné - ne to i.

2023-04-05 10:57 UTC, tomasma5 commented on src/main/java/cz/pf/Main.java
> +                        continue;
jsi si jistá, že to funguje? zkoušela jsi to?

2023-04-05 10:57 UTC, tomasma5 commented on src/main/java/cz/pf/Main.java
> +            ifCorrect = true;
proč tady nastavuješ true? nahoře si true nastavila ne?

2023-04-05 11:10 UTC, anchutkina commented on src/main/java/cz/pf/Main.java
> +            ifCorrect = true;
@tomasma5 
Protože bez toho ifCorrect bude furt false, když user uvede něco špatně a bude loop furt ptat, i když už to zadá spravně. Jako na obrázku. 
![random](https://user-images.githubusercontent.com/125275776/230063775-b48024af-2279-427a-994b-f6dcfc793b5b.png)

2023-04-05 11:17 UTC, anchutkina commented on src/main/java/cz/pf/Main.java
> +                        continue;
@tomasma5 
Zkoušela jsem, všechno fungovalo :)
Přidala jsem do main tohle, aby to fungovalo:
![menu](https://user-images.githubusercontent.com/125275776/230064909-75ce1d9d-d943-4e84-97f5-d16d10011493.png)

Je v tom něco špatně?

2023-04-05 11:53 UTC, tomasma5 commented on src/main/java/cz/pf/Main.java
> +                        continue;
No continue má vliv na cykl v kterém si a tady to jedeš v tom for cyklu ne? Nikoliv v tom while? nebo to GitHub špatně zobrazuje ;)

2023-04-05 11:55 UTC, tomasma5 commented on src/main/java/cz/pf/Main.java
> +            ifCorrect = true;
Trochu mi to není jasné. ifCorrect na řádku 151 nastavíš na true, pak znovu na 153. Nemá to pak logiku :)
Podle mě máš špatně tu podmínku. Ty chceš aby ten while pokračoval, pokud je volba špatná ne? Tzn proč si dole v případě, že zadal něco co je špatně neresetuješ chosenArrayType? Pak by ses toho ifCorrect mohla zbavit.

2023-04-05 16:18 UTC, anchutkina commented on src/main/java/cz/pf/Main.java
> +            ifCorrect = true;
Opraveno :)

2023-04-05 16:19 UTC, anchutkina commented on src/main/java/cz/pf/Main.java
> +                        continue;
Smazala jsem zbytečný continue, nechala jsem jeden ve while

2023-04-17 12:51 UTC, merged